export const myAds = [
  {
    id: 1,
    title: 'Honda Civic',
    reviews: 4,
    city: 'Karachi',
    views: 0,
    updatedOn: '11 April 22',
    status: 'active',
  },
  {
    id: 2,
    title: 'Honda Civic 2',
    reviews: 4,
    city: 'Karachi',
    views: 0,
    updatedOn: '11 April 22',
    status: 'active',
  },
  {
    id: 3,
    title: 'Honda Civic 3',
    reviews: 4,
    city: 'Karachi',
    views: 0,
    updatedOn: '11 April 22',
    status: 'pending',
  },
  {
    id: 4,
    title: 'Honda Civic 4',
    reviews: 4,
    city: 'Karachi',
    views: 0,
    updatedOn: '11 April 22',
    status: 'pending',
  },
  {
    id: 5,
    title: 'Honda Civic 5',
    reviews: 4,
    city: 'Karachi',
    views: 0,
    updatedOn: '11 April 22',
    status: 'pending',
  },
  {
    id: 6,
    title: 'Honda Civic 6',
    reviews: 4,
    city: 'Karachi',
    views: 0,
    updatedOn: '11 April 22',
    status: 'removed',
  },
];

export const blogs = [
  {
    id: 1,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity blog pada UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 1,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity blog pada UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 2,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity blog pada UI',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 3,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 4,
    createdAt: 'July 05, 2021',
    title: 'Tentang  blog pada UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 5,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity  pada UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 6,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity blog pada UI',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 7,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 8,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity pada UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
  {
    id: 9,
    createdAt: 'July 05, 2021',
    title: 'Tentang Creactivity blog heh UI Designer',
    shortDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum.',
    mainImage: '/images/blogs/blogCover.jpg',
    blogContent: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempus dolor non est ultrices, vel pulvinar magna egestas. Ut porta aliquet ex, vitae interdum eros lacinia et. Quisque lectus elit, suscipit placerat erat sed, tincidunt lobortis ligula. Curabitur augue ligula, eleifend nec pretium sed, laoreet porta odio. Pellentesque id libero vitae odio laoreet sodales. Morbi accumsan quis purus in condimentum. Vivamus in nibh non elit iaculis dictum. Morbi augue elit, tempor et egestas in, interdum consequat felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nec nunc purus. Pellentesque ut ex semper, suscipit nunc sed, condimentum nisl. Praesent blandit orci vitae nisl consequat vulputate. Pellentesque dignissim vel erat eget tincidunt. Phasellus aliquam dignissim felis sit amet blandit.Fusce felis nisl, condimentum ac rutrum a, scelerisque sit amet justo. Pellentesque ac nunc ex. Nam quis bibendum enim. Aenean consectetur lectus feugiat massa dignissim, et accumsan quam bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam augue dui, porttitor sed sem vel, maximus vehicula metus. Suspendisse id tortor id lorem malesuada ornare eu at eros.
    Duis vestibulum, elit non sollicitudin ullamcorper, metus nibh dignissim sem, ut tempor velit elit vitae risus. Etiam dapibus leo nibh, ac blandit metus imperdiet eget.Nunc condimentum, urna a pretium elementum, lorem purus congue libero, ut vulputate dui ligula in quam. Curabitur in sollicitudin purus. Proin auctor, sapien vel imperdiet accumsan, nisi felis tincidunt dolor, sit amet ultrices eros nisi eget eros. Nunc in vestibulum erat. Vestibulum semper arcu leo, dignissim venenatis tortor vulputate non. Proin vel hendrerit metus, sit amet porta lectus. Fusce accumsan ante nec mauris congue feugiat.Curabitur bibendum mauris fringilla erat imperdiet pulvinar. Integer vitae sem congue, commodo est sed, gravida eros. Maecenas ac justo non ante posuere scelerisque. Quisque pretium eros quis elementum elementum. Phasellus euismod eros vitae velit lacinia, ac malesuada felis blandit. Proin quam lectus, porttitor quis ultricies a, molestie quis odio. Quisque augue leo, viverra sit amet malesuada id, iaculis rutrum orci. Integer placerat egestas risus, ut ullamcorper ligula vehicula eget.
    Cras interdum interdum dui, vel feugiat massa vestibulum sit amet. Maecenas aliquet sagittis dapibus. Sed lacinia, leo efficitur lobortis elementum, sem justo bibendum nulla, vel facilisis nisl lorem nec mauris. Suspendisse malesuada arcu in libero maximus congue. Aliquam at pharetra magna. Donec diam nibh, finibus in volutpat eu, ullamcorper eget quam. Praesent suscipit ipsum sit amet mauris luctus, quis mattis tellus finibus. Nunc semper dapibus eros a lacinia. Duis enim neque, venenatis vitae facilisis in, cursus et mi. Quisque venenatis justo eget ipsum imperdiet, ac lacinia quam vulputate. Aliquam tempus, magna a accumsan consequat, mi tortor rutrum quam, a dignissim tellus diam faucibus felis. Donec rutrum hendrerit dolor vel mollis. Aliquam erat volutpat. Quisque elementum sapien enim, sodales mattis ex tincidunt id. In hac habitasse platea dictumst. Fusce luctus molestie malesuada.`,
  },
];
